version: "3"

services:
  backend:
    image: cebackend
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    env_file: ".env"
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - "POSTGRES_DB=${CE_DB_NAME}"
      - "POSTGRES_USER=${CE_DB_USER}"
      - "POSTGRES_PASSWORD=${CE_DB_PWD}"
    ports:
      -   "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
