# Generated by Django 4.2.2 on 2023-06-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('lookup_identifiers', models.CharField(max_length=512)),
                ('unit', models.CharField(max_length=50)),
                ('co2e', models.FloatField()),
                ('scope', models.IntegerField(null=True)),
                ('category', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
