# Generated by Django 4.2.2 on 2023-06-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FilePathField()),
                ('file_path', models.FileField(upload_to='')),
            ],
        ),
    ]
