# Generated by Django 4.2.2 on 2023-06-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_emissionfactorfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionfactorfile',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='emissionfactorfile',
            name='file_name',
        ),
    ]
