# Generated by Django 4.2.2 on 2023-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0002_activitydatafile_emissionfactorfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(db_index=True, max_length=255)),
                ('co2e', models.FloatField()),
                ('scope', models.IntegerField(null=True)),
                ('category', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='activity',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
