# Generated by Django 4.2.2 on 2023-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emission', '0003_rename_file_path_emissionfactorfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactorfile',
            name='update_factors',
            field=models.BooleanField(default=True),
        ),
    ]
